ALTER TABLE teams DROP COLUMN IF EXISTS influence;
ALTER TABLE teams DROP COLUMN IF EXISTS experience;
ALTER TABLE teams DROP COLUMN IF EXISTS strength;
ALTER TABLE teams DROP COLUMN IF EXISTS intelligence;
ALTER TABLE teams DROP COLUMN IF EXISTS endurance;
ALTER TABLE teams DROP COLUMN IF EXISTS leadership;
ALTER TABLE teams DROP COLUMN IF EXISTS luck;
